"""Read-only structural validation of the acquired NSO corpus.

The validator scans all persisted PX-Web Parquet tables and representative current
NSO website workbooks. It checks coordinate uniqueness, dimension completeness,
workbook readability, formulas, merged cells, ditto notation, and temporal/header
evidence. It performs no network requests and does not modify raw data or registries.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
import unicodedata
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
import sys

PIPELINE_ROOT = Path(__file__).resolve().parents[1]
if str(PIPELINE_ROOT) not in sys.path:
    sys.path.insert(0, str(PIPELINE_ROOT))
from typing import Any, Iterable

import pandas as pd
from openpyxl import load_workbook

from src.paths import (
    PROJECT_ROOT,
    NSO_WEB_MONTHLY_ROOT,
    PXWEB_API_ROOT,
    PXWEB_HTML_ROOT,
)

# =============================================================================
# 0. CONFIGURATION
# =============================================================================

PX_ROOT = PXWEB_API_ROOT
PX_HTML_ROOT = PXWEB_HTML_ROOT
NSO_SERIES_ROOT = NSO_WEB_MONTHLY_ROOT
PRODUCTION_MANIFEST_TYPE = "nso_web_release_artifact_manifest"

EXPECTED_PX_TABLES = 492
EXPECTED_PRODUCTION_MANIFESTS = 321
EXPECTED_CURRENT_EXCEL_ARTIFACTS = 321

# We do not need to open all historical Website workbooks to validate the
# recurring current structure. Select recent current XLSX files, while also
# inventorying all current Excel artifacts from manifests.
RECENT_XLSX_LIMIT = 12

# Bound console output; full validation still scans all PX tables.
MAX_EXAMPLES = 15
MAX_SHEET_EXAMPLES = 30

# Technical columns generated by the PX acquisition layer. They are not
# statistical dimensions.
PX_TECHNICAL_COLUMNS = {"value", "value_raw"}


# =============================================================================
# 1. SMALL HELPERS
# =============================================================================

def heading(title: str) -> None:
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)


def subheading(title: str) -> None:
    print("\n" + title)
    print("-" * 100)


def norm_text(value: Any) -> str:
    if value is None:
        return ""
    text = " ".join(str(value).split()).casefold()
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    text = text.replace("³", "3").replace("²", "2")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def compact_text(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", norm_text(value))


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        obj = json.load(fh)
    if not isinstance(obj, dict):
        raise ValueError(f"Expected JSON object: {path}")
    return obj


def parse_date(value: Any) -> datetime:
    if not isinstance(value, str):
        return datetime.min
    text = value.strip()
    try:
        dt = datetime.fromisoformat(text.replace("Z", "+00:00"))
        return dt.replace(tzinfo=None) if dt.tzinfo else dt
    except ValueError:
        pass
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y"):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            pass
    return datetime.min


def safe_rel(path: Path) -> str:
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def scalar_key(value: Any) -> str:
    """Stable text representation for validation signatures only."""
    if value is None:
        return "<NULL>"
    try:
        if pd.isna(value):
            return "<NULL>"
    except Exception:
        pass

    if isinstance(value, float):
        if math.isnan(value):
            return "<NULL>"
        return repr(value)

    return str(value)


def coordinate_signature(columns: list[str], row: pd.Series) -> str:
    """
    Canonical validation signature based on dimension name + raw member value.

    This signature is only used to test whether the persisted source
    table has duplicate statistical coordinates after technical value columns
    are removed.
    """
    parts = []
    for col in columns:
        parts.append(f"{col}={scalar_key(row[col])}")
    return "\x1f".join(parts)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# =============================================================================
# 2. PX-WEB — ALL-TABLE VALIDATION
# =============================================================================

@dataclass
class PxTableResult:
    path: Path
    rows: int
    dimensions: list[str]
    dimension_count: int
    duplicate_coordinates: int
    null_dimension_cells: int
    signature_collision_count: int
    member_counts: dict[str, int]


def px_parquets() -> list[Path]:
    api_paths = list(
        PX_ROOT.rglob("*.parquet")
    )

    html_paths = list(
        PX_HTML_ROOT.rglob("*.parquet")
    )

    paths = sorted(
        api_paths + html_paths
    )

    if not paths:
        raise RuntimeError(
            "No PX Parquet files found under "
            f"{PX_ROOT} or {PX_HTML_ROOT}"
        )

    return paths

def validate_px_table(path: Path) -> PxTableResult:
    df = pd.read_parquet(path)

    if "value" not in df.columns and "value_raw" not in df.columns:
        raise RuntimeError(
            f"PX table has neither value nor value_raw technical column: {path}"
        )

    dimensions = [c for c in df.columns if c not in PX_TECHNICAL_COLUMNS]

    if not dimensions:
        # A zero-dimensional scalar dataset is theoretically representable,
        # but flag it explicitly because it is unusual in the current corpus.
        dimensions = []

    null_dimension_cells = 0
    member_counts: dict[str, int] = {}
    for col in dimensions:
        null_dimension_cells += int(df[col].isna().sum())
        member_counts[col] = int(df[col].nunique(dropna=False))

    # A statistical source row should be unique on its complete source-native
    # coordinate. Duplicate coordinates would require extra source semantics.
    if dimensions:
        duplicated = df.duplicated(subset=dimensions, keep=False)
        duplicate_coordinates = int(duplicated.sum())
    else:
        duplicate_coordinates = max(0, len(df) - 1)

    # Independently test the signature mechanism and detect theoretical hash
    # collisions inside this table.
    signature_to_coordinate: dict[str, str] = {}
    signature_collision_count = 0

    if dimensions:
        for _, row in df.iterrows():
            coordinate = coordinate_signature(dimensions, row)
            digest = sha256_text(coordinate)
            prior = signature_to_coordinate.get(digest)
            if prior is None:
                signature_to_coordinate[digest] = coordinate
            elif prior != coordinate:
                signature_collision_count += 1
    else:
        digest = sha256_text("<ZERO_DIMENSION_COORDINATE>")
        signature_to_coordinate[digest] = "<ZERO_DIMENSION_COORDINATE>"

    return PxTableResult(
        path=path,
        rows=len(df),
        dimensions=dimensions,
        dimension_count=len(dimensions),
        duplicate_coordinates=duplicate_coordinates,
        null_dimension_cells=null_dimension_cells,
        signature_collision_count=signature_collision_count,
        member_counts=member_counts,
    )


def validate_all_px() -> list[PxTableResult]:
    paths = px_parquets()

    subheading("PX persisted inventory")
    print(f"PX root                              : {PX_ROOT}")
    print(f"Parquet tables discovered            : {len(paths)}")
    print(f"Expected persisted PX tables         : {EXPECTED_PX_TABLES}")

    if len(paths) != EXPECTED_PX_TABLES:
        raise RuntimeError(
            f"Expected {EXPECTED_PX_TABLES} PX Parquet tables, found {len(paths)}."
        )

    results = []
    for i, path in enumerate(paths, start=1):
        result = validate_px_table(path)
        results.append(result)

        if i % 50 == 0 or i == len(paths):
            print(f"Validated PX tables                  : {i}/{len(paths)}")

    return results


def report_px(results: list[PxTableResult]) -> dict[str, Any]:
    subheading("PX N-dimensional representability")

    dim_distribution = Counter(r.dimension_count for r in results)
    max_dim = max((r.dimension_count for r in results), default=0)
    min_dim = min((r.dimension_count for r in results), default=0)
    total_rows = sum(r.rows for r in results)
    dup_tables = [r for r in results if r.duplicate_coordinates > 0]
    null_dim_tables = [r for r in results if r.null_dimension_cells > 0]
    collision_tables = [r for r in results if r.signature_collision_count > 0]

    print(f"Total PX rows                         : {total_rows:,}")
    print(f"Minimum dimensions/table              : {min_dim}")
    print(f"Maximum dimensions/table              : {max_dim}")
    print(f"Dimension-count distribution          : {dict(sorted(dim_distribution.items()))}")
    print(f"Tables with duplicate coordinates     : {len(dup_tables)}")
    print(f"Tables with NULL dimension cells      : {len(null_dim_tables)}")
    print(f"Tables with SHA-256 signature collision: {len(collision_tables)}")

    widest = sorted(
        results,
        key=lambda r: (r.dimension_count, r.rows),
        reverse=True,
    )[:MAX_EXAMPLES]

    print("\nWidest PX table examples:")
    for r in widest:
        print(
            f"- {safe_rel(r.path)} | rows={r.rows:,} | "
            f"dims={r.dimension_count} | {r.dimensions}"
        )

    if dup_tables:
        print("\nPX duplicate-coordinate exceptions:")
        for r in dup_tables[:MAX_EXAMPLES]:
            print(
                f"- {safe_rel(r.path)} | "
                f"duplicate rows={r.duplicate_coordinates:,} | dims={r.dimensions}"
            )

    if null_dim_tables:
        print("\nPX NULL-dimension examples:")
        for r in null_dim_tables[:MAX_EXAMPLES]:
            print(
                f"- {safe_rel(r.path)} | "
                f"NULL dimension cells={r.null_dimension_cells:,}"
            )

    return {
        "table_count": len(results),
        "total_rows": total_rows,
        "min_dim": min_dim,
        "max_dim": max_dim,
        "dim_distribution": dict(sorted(dim_distribution.items())),
        "duplicate_tables": len(dup_tables),
        "null_dimension_tables": len(null_dim_tables),
        "collision_tables": len(collision_tables),
    }


# =============================================================================
# 3. NSO WEBSITE — MANIFEST + CURRENT EXCEL INVENTORY
# =============================================================================

def current_revision(artifact: dict[str, Any]) -> dict[str, Any] | None:
    current = artifact.get("current_revision")
    revisions = artifact.get("revisions")
    if not isinstance(revisions, list):
        return None
    for rev in revisions:
        if isinstance(rev, dict) and rev.get("revision_number") == current:
            return rev
    return None


def resolve_current_artifact(
    stored: str,
    manifest_path: Path,
) -> tuple[Path | None, str | None]:
    raw = Path(stored)

    candidates: list[tuple[Path, str]] = []
    if raw.is_absolute():
        candidates.append((raw, "absolute"))
    else:
        candidates.extend(
            [
                (PROJECT_ROOT / raw, "project_relative"),
                (NSO_SERIES_ROOT / raw, "series_relative"),
                (manifest_path.parent / raw, "manifest_relative"),
            ]
        )

        # Some stored paths may include the release folder while manifest_path
        # already points inside that release folder.
        if raw.parts and raw.parts[0] == manifest_path.parent.name:
            candidates.append(
                (
                    manifest_path.parent.parent / raw,
                    "manifest_parent_plus_release_relative",
                )
            )

    seen = set()
    for path, mode in candidates:
        key = str(path)
        if key in seen:
            continue
        seen.add(key)
        if path.is_file():
            return path, mode

    return None, None


def production_manifests() -> list[tuple[Path, dict[str, Any]]]:
    out = []
    ignored = 0

    for path in NSO_SERIES_ROOT.rglob("manifest.json"):
        try:
            manifest = load_json(path)
        except Exception:
            ignored += 1
            continue

        if manifest.get("manifest_type") != PRODUCTION_MANIFEST_TYPE:
            ignored += 1
            continue

        out.append((path, manifest))

    print(f"Production manifests                  : {len(out)}")
    print(f"Ignored non-production/invalid        : {ignored}")

    if len(out) != EXPECTED_PRODUCTION_MANIFESTS:
        raise RuntimeError(
            f"Expected {EXPECTED_PRODUCTION_MANIFESTS} production manifests, "
            f"found {len(out)}."
        )

    return out


def current_excel_inventory(
    manifests: list[tuple[Path, dict[str, Any]]],
) -> list[dict[str, Any]]:
    records = []
    missing = []

    for manifest_path, manifest in manifests:
        snapshot = manifest.get("release_snapshot")
        if not isinstance(snapshot, dict):
            snapshot = {}

        for artifact in manifest.get("artifacts", []):
            if not isinstance(artifact, dict):
                continue
            if artifact.get("artifact_type") != "excel":
                continue

            rev = current_revision(artifact)
            if rev is None:
                missing.append((manifest_path, "missing current revision"))
                continue

            stored = rev.get("local_relative_path")
            if not isinstance(stored, str) or not stored.strip():
                missing.append((manifest_path, "missing local_relative_path"))
                continue

            physical, resolution_mode = resolve_current_artifact(stored, manifest_path)
            if physical is None:
                missing.append((manifest_path, stored))
                continue

            records.append(
                {
                    "manifest_path": manifest_path,
                    "manifest": manifest,
                    "snapshot": snapshot,
                    "artifact": artifact,
                    "revision": rev,
                    "path": physical,
                    "resolution_mode": resolution_mode,
                    "publication_date": parse_date(snapshot.get("publication_date")),
                }
            )

    print(f"Current Excel artifacts resolved      : {len(records)}")
    print(f"Current Excel resolution failures     : {len(missing)}")

    if missing:
        for item in missing[:MAX_EXAMPLES]:
            print(f"  unresolved: {item}")

    if len(records) != EXPECTED_CURRENT_EXCEL_ARTIFACTS:
        raise RuntimeError(
            f"Expected {EXPECTED_CURRENT_EXCEL_ARTIFACTS} current Excel artifacts, "
            f"resolved {len(records)}."
        )

    return records


# =============================================================================
# 4. NSO WEBSITE — REPRESENTATIVE WORKBOOK STRUCTURE
# =============================================================================

TEMPORAL_TERMS = (
    "thang",
    "quy",
    "nam",
    "cung ky",
    "so voi",
    "yoy",
    "luy ke",
    "thuc hien",
)

UNIT_TERMS = (
    "don vi",
    "dvt",
    "%",
    "tan",
    "m3",
    "lit",
    "kwh",
    "dong",
    "cai",
    "chiec",
    "doi",
    "nguoi",
    "doanh nghiep",
)


@dataclass
class SheetEvidence:
    workbook: Path
    sheet: str
    max_row: int
    max_column: int
    merged_ranges: int
    formula_cells: int
    ditto_cells: int
    temporal_text_cells: int
    unit_like_text_cells: int
    nonempty_cells: int
    hierarchy_channel_rows: int


def cell_text(value: Any) -> str:
    return " ".join(str(value).split()) if value is not None else ""


def inspect_sheet_evidence(ws) -> SheetEvidence:
    formula_cells = 0
    ditto_cells = 0
    temporal_text_cells = 0
    unit_like_text_cells = 0
    nonempty_cells = 0

    # Evidence of hierarchical presentation channels: in the first four
    # columns, count rows with text in at least one channel. This does not
    # assert fixed hierarchy levels; it only detects presentation structure.
    hierarchy_channel_rows = 0

    for row in ws.iter_rows():
        first_four_text = 0

        for cell in row:
            value = cell.value
            if value is None:
                continue

            nonempty_cells += 1

            if isinstance(value, str):
                stripped = value.strip()

                if stripped.startswith("="):
                    formula_cells += 1

                if stripped in {'"', "''", "”", "“"}:
                    ditto_cells += 1

                n = norm_text(stripped)
                if any(term in n for term in TEMPORAL_TERMS):
                    temporal_text_cells += 1

                if any(term in n for term in UNIT_TERMS):
                    unit_like_text_cells += 1

                if cell.column <= 4 and stripped:
                    first_four_text += 1

            # openpyxl formulas are strings beginning with "=" when
            # data_only=False. Keep this second check for safety.
            elif getattr(cell, "data_type", None) == "f":
                formula_cells += 1

        if first_four_text:
            hierarchy_channel_rows += 1

    return SheetEvidence(
        workbook=Path(ws.parent.properties.title or ""),
        sheet=ws.title,
        max_row=ws.max_row,
        max_column=ws.max_column,
        merged_ranges=len(ws.merged_cells.ranges),
        formula_cells=formula_cells,
        ditto_cells=ditto_cells,
        temporal_text_cells=temporal_text_cells,
        unit_like_text_cells=unit_like_text_cells,
        nonempty_cells=nonempty_cells,
        hierarchy_channel_rows=hierarchy_channel_rows,
    )


def select_recent_xlsx(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    xlsx = [r for r in records if r["path"].suffix.casefold() == ".xlsx"]
    xlsx.sort(
        key=lambda r: (r["publication_date"], str(r["path"])),
        reverse=True,
    )
    return xlsx[:RECENT_XLSX_LIMIT]


def inspect_recent_workbooks(
    records: list[dict[str, Any]],
) -> dict[str, Any]:
    selected = select_recent_xlsx(records)

    print(f"Recent XLSX selected                  : {len(selected)}")
    if not selected:
        raise RuntimeError("No current .xlsx files available for Website validation.")

    sheet_name_counter = Counter()
    sheet_count_distribution = Counter()
    sheet_evidence: list[dict[str, Any]] = []
    workbook_failures = []
    formula_workbooks = 0
    ditto_workbooks = 0
    merged_workbooks = 0
    temporal_workbooks = 0
    hierarchy_workbooks = 0

    for rec in selected:
        path = rec["path"]

        try:
            wb = load_workbook(
                path,
                read_only=False,
                data_only=False,
            )
        except Exception as exc:
            workbook_failures.append((path, repr(exc)))
            continue

        workbook_has_formula = False
        workbook_has_ditto = False
        workbook_has_merge = False
        workbook_has_temporal = False
        workbook_has_hierarchy = False

        sheet_count_distribution[len(wb.sheetnames)] += 1

        for ws in wb.worksheets:
            sheet_name_counter[compact_text(ws.title)] += 1

            ev = inspect_sheet_evidence(ws)
            ev_dict = {
                "workbook": path,
                "sheet": ws.title,
                "max_row": ev.max_row,
                "max_column": ev.max_column,
                "merged_ranges": ev.merged_ranges,
                "formula_cells": ev.formula_cells,
                "ditto_cells": ev.ditto_cells,
                "temporal_text_cells": ev.temporal_text_cells,
                "unit_like_text_cells": ev.unit_like_text_cells,
                "nonempty_cells": ev.nonempty_cells,
                "hierarchy_channel_rows": ev.hierarchy_channel_rows,
            }
            sheet_evidence.append(ev_dict)

            workbook_has_formula |= ev.formula_cells > 0
            workbook_has_ditto |= ev.ditto_cells > 0
            workbook_has_merge |= ev.merged_ranges > 0
            workbook_has_temporal |= ev.temporal_text_cells > 0
            workbook_has_hierarchy |= ev.hierarchy_channel_rows > 0

        wb.close()

        formula_workbooks += int(workbook_has_formula)
        ditto_workbooks += int(workbook_has_ditto)
        merged_workbooks += int(workbook_has_merge)
        temporal_workbooks += int(workbook_has_temporal)
        hierarchy_workbooks += int(workbook_has_hierarchy)

    print(f"Recent XLSX readable                  : {len(selected) - len(workbook_failures)}")
    print(f"Workbook failures                     : {len(workbook_failures)}")
    print(f"Workbook sheet-count distribution     : {dict(sorted(sheet_count_distribution.items()))}")
    print(f"Workbooks with formulas               : {formula_workbooks}")
    print(f"Workbooks with ditto cells            : {ditto_workbooks}")
    print(f"Workbooks with merged cells           : {merged_workbooks}")
    print(f"Workbooks with temporal text evidence : {temporal_workbooks}")
    print(f"Workbooks with hierarchy-channel text : {hierarchy_workbooks}")

    if workbook_failures:
        for path, err in workbook_failures:
            print(f"  workbook failure: {safe_rel(path)} -> {err}")

    print("\nRecent workbook inventory:")
    for rec in selected:
        snap = rec["snapshot"]
        print(
            f"- {rec['path'].name} | "
            f"publication={snap.get('publication_date')} | "
            f"reference={snap.get('reference_period')} | "
            f"resolution={rec['resolution_mode']}"
        )

    print("\nMost recurrent normalized sheet-name tokens:")
    for name, count in sheet_name_counter.most_common(MAX_SHEET_EXAMPLES):
        print(f"- {name!r}: {count}/{len(selected)}")

    # Bounded structural examples.
    print("\nBounded sheet evidence:")
    for ev in sheet_evidence[:MAX_SHEET_EXAMPLES]:
        print(
            f"- {ev['workbook'].name} :: {ev['sheet']} | "
            f"shape={ev['max_row']}x{ev['max_column']} | "
            f"merges={ev['merged_ranges']} | "
            f"formulas={ev['formula_cells']} | "
            f"ditto={ev['ditto_cells']} | "
            f"temporal_text={ev['temporal_text_cells']}"
        )

    return {
        "selected": len(selected),
        "readable": len(selected) - len(workbook_failures),
        "failures": len(workbook_failures),
        "sheet_count_distribution": dict(sorted(sheet_count_distribution.items())),
        "formula_workbooks": formula_workbooks,
        "ditto_workbooks": ditto_workbooks,
        "merged_workbooks": merged_workbooks,
        "temporal_workbooks": temporal_workbooks,
        "hierarchy_workbooks": hierarchy_workbooks,
        "sheet_evidence": sheet_evidence,
    }


# =============================================================================
# 5. STRUCTURAL AUDIT
# =============================================================================

def structural_audit(
    px_summary: dict[str, Any],
    website_summary: dict[str, Any],
) -> list[tuple[str, str, str]]:
    """
    Return rows: (assumption, status, evidence/reason).

    PASS means current persisted evidence satisfies the structural check.
    REVIEW means the acquired corpus exposes an exception that should be investigated.
    """
    audit = []

    audit.append(
        (
            "PX tables have valid variable N-dimensional coordinates",
            "PASS" if px_summary["table_count"] == EXPECTED_PX_TABLES else "REVIEW",
            (
                f"{px_summary['table_count']} tables; "
                f"dimension range {px_summary['min_dim']}..{px_summary['max_dim']}"
            ),
        )
    )

    audit.append(
        (
            "PX coordinate signatures do not suffer observed SHA-256 collisions",
            "PASS" if px_summary["collision_tables"] == 0 else "REVIEW",
            f"tables with observed collision={px_summary['collision_tables']}",
        )
    )

    audit.append(
        (
            "PX source rows are unique on all non-technical columns",
            "PASS" if px_summary["duplicate_tables"] == 0 else "REVIEW",
            f"tables with duplicate full source coordinates={px_summary['duplicate_tables']}",
        )
    )

    audit.append(
        (
            "PX dimensions do not require NULL-as-member semantics",
            "PASS" if px_summary["null_dimension_tables"] == 0 else "REVIEW",
            f"tables with NULL dimension cells={px_summary['null_dimension_tables']}",
        )
    )

    audit.append(
        (
            "Website recurring releases provide readable repeated workbook instances",
            "PASS" if website_summary["readable"] > 1 else "REVIEW",
            (
                f"recent XLSX readable={website_summary['readable']}; "
                f"sheet-count distribution={website_summary['sheet_count_distribution']}"
            ),
        )
    )

    audit.append(
        (
            "Website workbooks contain formulas that acquisition must preserve",
            "PASS" if website_summary["formula_workbooks"] > 0 else "REVIEW",
            f"recent workbooks with formulas={website_summary['formula_workbooks']}",
        )
    )

    audit.append(
        (
            "Website workbooks contain ditto notation that acquisition must preserve",
            "PASS" if website_summary["ditto_workbooks"] > 0 else "REVIEW",
            f"recent workbooks with ditto cells={website_summary['ditto_workbooks']}",
        )
    )

    audit.append(
        (
            "Website workbooks contain merged-cell physical layout",
            "PASS" if website_summary["merged_workbooks"] > 0 else "REVIEW",
            f"recent workbooks with merged cells={website_summary['merged_workbooks']}",
        )
    )

    audit.append(
        (
            "Website workbooks contain non-trivial temporal/header text",
            "PASS" if website_summary["temporal_workbooks"] > 0 else "REVIEW",
            f"recent workbooks with temporal header/text evidence={website_summary['temporal_workbooks']}",
        )
    )

    return audit


# =============================================================================
# 6. MAIN
# =============================================================================

def main() -> None:
    heading("ACQUIRED-DATA STRUCTURAL VALIDATION")

    print(f"Project root                         : {PROJECT_ROOT}")
    print("Network requests                     : NO")
    print("Production acquisition               : NOT RUN")
    print("Registry/manifest/raw modifications  : NO")
    print("Cross-source fuzzy mapping           : NO")

    # ---------------------------------------------------------------------
    # PX
    # ---------------------------------------------------------------------
    heading("A — PX-WEB PERSISTED TABLES")
    px_results = validate_all_px()
    px_summary = report_px(px_results)

    # ---------------------------------------------------------------------
    # Website
    # ---------------------------------------------------------------------
    heading("B — NSO WEBSITE: PRODUCTION INVENTORY + RECENT WORKBOOKS")

    manifests = production_manifests()
    excel_records = current_excel_inventory(manifests)

    suffix_counts = Counter(r["path"].suffix.casefold() for r in excel_records)
    resolution_counts = Counter(r["resolution_mode"] for r in excel_records)

    print(f"Current Excel suffix distribution    : {dict(sorted(suffix_counts.items()))}")
    print(f"Path resolution modes                : {dict(sorted(resolution_counts.items()))}")

    website_summary = inspect_recent_workbooks(excel_records)

    # ---------------------------------------------------------------------
    # Assumption audit
    # ---------------------------------------------------------------------
    heading("C — STRUCTURAL AUDIT")

    audit = structural_audit(px_summary, website_summary)
    review_rows = []

    for assumption, status, evidence in audit:
        print(f"[{status}] {assumption}")
        print(f"       {evidence}")
        if status != "PASS":
            review_rows.append((assumption, evidence))

    # ---------------------------------------------------------------------
    # Decision
    # ---------------------------------------------------------------------
    heading("VALIDATION DECISION")

    print(f"PX tables validated                   : {px_summary['table_count']}")
    print(f"PX persisted rows validated           : {px_summary['total_rows']:,}")
    print(
        f"PX dimension-count range              : "
        f"{px_summary['min_dim']}..{px_summary['max_dim']}"
    )
    print(f"Production Website manifests          : {len(manifests)}")
    print(f"Current Website Excel artifacts       : {len(excel_records)}")
    print(f"Recent Website XLSX structurally read : {website_summary['readable']}")
    print(f"Structural checks needing review      : {len(review_rows)}")

    if review_rows:
        print("\nREVIEW REQUIRED — acquired-data structural checks exposed exceptions:")
        for assumption, evidence in review_rows:
            print(f"- {assumption}")
            print(f"  {evidence}")

        raise RuntimeError(
            "Acquired-data validation exposed one or more structural checks "
            "requiring review."
        )

    print("\nPASS — current persisted PX-Web and representative NSO Website")
    print("artifacts satisfy the acquisition structural checks.")
    print("")
    print("IMPORTANT:")
    print("- This PASS validates persisted source structure and readability.")
    print("- It does not assert cross-source semantic equivalence.")


if __name__ == "__main__":
    main()
